#!/bin/sh

# exit on error and echo commands for debugging assist
set -e
set -x

[ -e Makefile ] && make clean
rm -rf Makefile Makefile.in src/Makefile src/.deps
rm -rf configure config.h config.h.in \
	config.log config.status \
	autom4te.cache aclocal.m4 stamp-h1 \
	depcomp missing install-sh \
	m4 build-aux
mkdir -p m4
mkdir -p build-aux

# Run the autoreconf steps
autoreconf -i -s
