#!/bin/sh

# exit on error and echo commands for debugging assist
set -e
set -x

[ -e Makefile ] && make clean
rm -rf autom4te.cache config.log configure Makefile stamp-h1
rm -rf src/Makefile src/.deps
rm -rf Makefile.in aclocal.m4 config.log config.h
rm -rf depcomp missing install-sh config.status
[ ! -d m4 ] && mkdir m4

# Run the autoreconf steps
autoreconf -i -s
