name: checks

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  commit-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  cmake-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install cmakelang
        run: |
          python -m pip install --upgrade pip cmakelang pyyaml
      - name: find cmakefiles
        id: find
        run: |
          files=$(find src \
                       -type f -iname "CMakeLists.txt" -o -iname "*.cmake")
          # do not quote to keep this a single line
          echo cmake_files=${files} >> $GITHUB_OUTPUT
      - name: check cmakefiles
        run: |
          cmake-lint -linfo --line-width 100 --tab-size 4 \
              ${{ steps.find.outputs.cmake_files }}
